---
title: "Time series visualizations"
author: "RvB"
format: 
  html:
    toc: true
    embed-resources: true
editor: visual
---

## pkgs
---

```{r}
#| message: false
library(tidyverse)
library(fpp3)
library(plotly)
library(patchwork)
library(tidyquant)
```

## 

```{r}
aus_accommodation
```

 

```{r}
# ALT +  "-" <-
# CTRL + SHIFT + M   |> 
tasmania <- aus_accommodation |> 
  filter(State=="Tasmania") |> 
  #select(-CPI, -State)
  select(-c(CPI, State))|> 
  # select(Date:Occupancy)
  # select(Date, State, Takings, Occupancy)
  mutate(
    `Año unión N°1` = 1
  ) |> 
    janitor::clean_names()

tasmania

tasmania |> 
  glimpse()
names(tasmania)

```

library(tidyverse) #pkgs for data science
library(fpp3) # pkgs for ts
library(plotly) # plotly interactive plots
library(patchwork) # for handling many plots in one figure
library(tidyquant) # toolkit for financial analysis and downloading data
```{r}
tasmania |> 
  autoplot(takings,color="slateblue1",size=2)+geom_point()
```

```{r}
tasmania |> 
  gg_season(log(takings))

tasmania |> 
  gg_subseries(log(takings))
```

```{r}
tasmania |> 
  gg_tsdisplay(log(takings),plot_type = "auto") #"auto", "partial", "season", "histogram", "scatter", "spectrum"
```

```{r}
stocks <- c("TSLA","GOOGL","MSFT","AAPL","CEMEXCPO.MX")

stocks_data <- tq_get(
  x=stocks,
  get="stock.prices",
  from="2014-01-01",
  to=today()-1
)

stocks_data
stocks_data |> 
  distinct(symbol)

stocks_data <- stocks_data |> 
  as_tsibble(index=date,key=symbol)

stocks_data
```

